# Generated by Django 4.2 on 2023-04-19 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0004_fotografias_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fotografias',
            name='foto',
            field=models.ImageField(blank=True, upload_to='fotos/%Y/%m/%d/'),
        ),
    ]
